# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-26 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='note',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('1', '\u603b\u76d1'), ('2', '\u7ecf\u7406'), ('3', '\u7814\u53d1')], default='3', max_length=4),
        ),
    ]
