# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-08 06:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0003_auto_20180506_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatistics',
            name='statime',
            field=models.DateField(default=datetime.date(2018, 5, 7), verbose_name='\u5904\u7406\u5b8c\u6210\u65f6\u95f4'),
        ),
    ]
